name: Send email via EN SMTP (simple test)

on:
  push:
    branches:
      - main

jobs:
  email:
    runs-on: ubuntu-latest

    steps:
      - name: Install SMTP client
        run: sudo apt-get update && sudo apt-get install -y swaks

      - name: Send test email
        run: |
          swaks \
            --to deepthiramesh.chandra@ibm.com \
            --from test@mailx.event-notifications.test.cloud.ibm.com \
            --server smtp.us-south.event-notifications.test.cloud.ibm.com \
            --port 587 \
            --auth PLAIN \
            --auth-user ${{ secrets.EN_SMTP_USER }} \
            --auth-password ${{ secrets.EN_SMTP_PASSWORD }} \
            --header "Subject: GitHub Actions SMTP test" \
            --body "This email was sent from GitHub Actions using En SMTP."
